flags = "-Wall -g -std=gnu11"
env = Environment(CC = "gcc", CCFLAGS = flags)
src = [
	"main.c",
	"oglTools.c",
	"fileTools.c",
	"cleanTxtFile.c",
	"misc.c",
	"optionsAndErrors.c",
	"timestamp.c",
	"fromHue.c",
	"initBounceEnv.c",
	"initWindow.c",
	"initSprites.c",
	"initOpenGl.c",
	"drawSpiro.c",
	"handleEvents.c",
	"mainMenuLoop.c",
	"glyphReactorLoop.c",
	"spiroViewerLoop.c",
	"cleanup.c",
	"frameLoop.c"
]
env.Program("GlyphReactor", src, LIBS = ["GL", "GLEW", "SDL2", "m", "png"])
